### ISSUE TITLE
How to publish Musicbee playback stats to MQTT?

### ISSUE THREAD

**Issue by fusionstream** [TroyFernandes/hass-mqtt-mediaplayer#8]
Sorry if this is an ignorant question or indeed if this could be construed as a support question.

But, how does one publish musicbee to MQTT in the first place?

**Comment by TroyFernandes** [comment]
I made a simple mqtt plugin for musicbee. However It's very quick and dirty which is why I havent released that plugin. 

I probably won't release it as I don't really have the time to fix it up to make it OK for releasing it for others to use. Sorry about that :(

**Comment by fusionstream** [comment]
Ah. That's a shame. 

If you ever get around to changing your mind though, maybe release it anyway as open source; like this one. That way someone could come along and fix it up.

Cheers

**Comment by iophobia** [comment]
I would also be interested in said plugin since MusicBee is my go-to player on PC and would be nice to have it incorporated to HASS for automations (door bell ring etc).
Best,
io

**Comment by bositman** [comment]
Any chance this seeing the light of day? No one else seems to have a way to connect MusicBee to Home assistant and this sounds like the best shot we have...

**Comment by sumoneelse** [comment]
If you're interested in a one-way link (Musicbee -> Home Assistant) I have MusicBee populating a "now playing" type of card in Home Assistant using the [Now Playing to External Files](https://www.getmusicbee.com/addons/plugins/47/now-playing-to-external-files/) plugin.  It is not for the faint of heart.  Once you've got the data into Home Assistant you can do anything you want with it, like publishing to MQTT.

Overview of my workflow:

MusicBee side (via the plugin):  
- Export Artist, Track, Album, Year to a tags file in a place on your network readable by HA
- Export Album Artwork to an image file that can be served via http

Home Assistant side:
- Use a file sensor to detect and read changes to the metadata file (I found this easiest to do in Node-RED)
- Use the generic camera plugin to read the album artwork via HTTP as a camera image
- Horizontal stack card with picture entity card (showing my fake camera) and a markdown card on the right (showing metadata)

End result is below/attached:

![Screenshot_20231207-102503](https://github.com/TroyFernandes/hass-mqtt-mediaplayer/assets/19894078/d5bbb064-a009-47c9-9279-a15fe553ba57)

**Comment by TroyFernandes** [comment]
Hey, I know you probably spent a lot of time with this setup, but I just uploaded the code of what I've been using these past few years over on this repo https://github.com/TroyFernandes/Musicbee-MQTT

I lost the code for the project a long time ago but found a backup recently, but the MQTT package for C# changed a little over the years so I just spent some time updating the code. 

If you decide to try the plugin, let me know how (and if) it works for you. 

Thanks

**Comment by sumoneelse** [comment]
This is awesome @TroyFernandes - thank you for coming out of deep retirement to make this available!  I am most of the way there but am a tiny bit stuck and hoping you can kick me the rest of the way to completion.  Documenting what I've done here for you and anyone else reading this thread:

Working/Done:
- Added hass-mqtt-mediaplayer custom component & entity to config.yaml
- Musicbee player config (verified I'm seeing everything published as expected via MQTT Explorer)
- Able to control Musicbee using direct service calls (dev tools) to the media player entity

Not working:
- No artwork or track info showing up in HA media player card (or mini-media player card)

By what mechanism does the track info & artwork get populated into the HA media player?  Do I need to create some sensors manually?

**Comment by TroyFernandes** [comment]
Yes, you'd have to create sensors.

Ill just show you how I have mine setup.

I have a [media_player](https://www.home-assistant.io/integrations/media_player/) entity in my configuration.yaml with the following:

```
- platform: mqtt-mediaplayer
  name: "Musicbee"
  topic:
    song_title: "{{ states('sensor.musicbee_song_title') }}"
    song_artist: "{{ states('sensor.musicbee_song_artist') }}"
    song_album: "{{ states('sensor.musicbee_song_album') }}"
    song_volume: "{{ states('sensor.musicbee_player_volume') }}"
    player_status: "{{ states('sensor.musicbee_player_status') }}"
    album_art: "musicbee/song/albumart"
    volume:
      service: mqtt.publish
      data:
        topic: "musicbee/command"
        payload: "{\"command\":\"volume_set\", \"args\":{\"volume\":\"{{volume}}\"}}"
  status_keyword: "true"
  next:
    service: mqtt.publish
    data:
      topic: "musicbee/command"
      payload: "{\"command\": \"next\"}"
  previous:
    service: mqtt.publish
    data:
      topic: "musicbee/command"
      payload: "{\"command\": \"previous\"}"
  play:
    service: mqtt.publish
    data:
      topic: "musicbee/command"
      payload: "{\"command\": \"play\"}"
  pause:
    service: mqtt.publish
    data:
      topic: "musicbee/command"
      payload: "{\"command\": \"pause\"}"
```

and then I have a sensor entity as well with the following:

```
sensor:
  - state_topic: "musicbee/song/title"
    name: "Musicbee_Song_Title"
  - state_topic: "musicbee/song/artist"
    name: "Musicbee_Song_Artist"
  - state_topic: "musicbee/song/album"
    name: "Musicbee_Song_Album"
  - state_topic: "musicbee/player/volume"
    name: "Musicbee_Player_Volume"
    icon: "mdi:volume-medium"
  - state_topic: "musicbee/player/playing"
    name: "Musicbee_Player_Status"
    icon: "mdi:volume-medium"
```

**Comment by sumoneelse** [comment]
I was just missing the sensors - 100% working now!  And for anyone else setting this up, they go under your MQTT integration key.

Tomorrow I will take a long look at the hacky solution I documented above, maybe archive it, and then rip it out.  : )

**Comment by TroyFernandes** [comment]
Glad its working for you now!

**Comment by bositman** [comment]
Thanks for this very much appreciated :)
Only one hiccup for me here, what kind of sensor do I need for album art? Neither one of these work:
mqtt:
 sensor:
  - name: "MusicBee Album Art test"
    state_topic: "musicbee/song/albumart"
is always "unknown"

and
mqtt:
  image:
  - name: "MusicBee Album Art"
    image_topic: musicbee/song/albumart
    content_type: image/png
    image_encoding: b64    

shows artwork fine but not sure how to use it on the mediaplayer entity declaration to show up.

Many thanks again :)

**Comment by sumoneelse** [comment]
Unlike the text tags, you do not need to create a sensor for the artwork. It is encoded in base64 into an MQTT topic:
![image](https://github.com/TroyFernandes/hass-mqtt-mediaplayer/assets/19894078/0e4b0382-6ea0-4e29-a15c-7ed50739eca3)
...which the mqtt-mediaplayer entity definition in your configuration.yaml can reference directly.  In @TroyFernandes's [post](https://github.com/TroyFernandes/hass-mqtt-mediaplayer/issues/8#issuecomment-1846211718) above, it's this line:

    album_art: "musicbee/song/albumart"

**Comment by bositman** [comment]
Hmm ok I tried setting it up like that as well but still no go. Are you using HAs built in media player entity to display to your dashboard? Maybe I'm missing something GUI wise...

**Comment by sumoneelse** [comment]
I just verified that yes indeed HA's built-in media player entity is picking up the artwork for me.  I personally use [mini-media-player](https://github.com/kalkih/mini-media-player) which is also picking it up.

Have you tried using MQTT Explorer or something of that nature to verify your MQTT artwork topic is being populated by Musicbee?  You may also need to play the next track in musicbee to trigger a publish.

**Comment by bositman** [comment]
Ah I think I found the issue on the console log, I'm getting error 500 from the nginx proxy addon probably, will have to debug it now..thanks for the help :)

**Comment by ElEmFurt** [comment]
After some tinkering around (I had to add the dll as a plugin in MusicBee, it wasnt obv to me sadly), I got this working with HA and it's a charm to see it in play, as I have been using MusicBee for more years than I can remember and having it now show up in HA is just perfect, thanks Troy for building this :)

**Comment by TroyFernandes** [comment]
Hello,

I updated both the [musicbee mqtt](https://github.com/TroyFernandes/Musicbee-MQTT/releases) plugin as well as the hass-mqtt-mediaplayer integration. The changes are in the [dev](https://github.com/TroyFernandes/hass-mqtt-mediaplayer/tree/dev) branch.

If you're willing to try out the new changes early, you just need to download the new .dll for musicbee, as well change the contents of ``media_player.py`` found [here](https://github.com/TroyFernandes/hass-mqtt-mediaplayer/blob/dev/custom_components/mqtt-mediaplayer/media_player.py)

Make sure you take a look at the example in the [README here](https://github.com/TroyFernandes/hass-mqtt-mediaplayer/tree/dev?tab=readme-ov-file#example-configurationyaml). You should be able to just copy and paste in your configuration.yaml/wherever you have it stored. Some fields like Genre, Year, etc. are not necessary unless you want that info.

One feature that "might not work" is the source selection. You might encounter that the drop-down for selecting the output source within the homeassistant UI might not do anything. But if you go to ``Settings -> Developer tools -> Actions tab -> Search for "select source" in the action box -> Add musicbee as the target -> type in your source **exactly** into the text box -> Perform action``, then it should work. I can't tell right now if its a bug in the HA ui or something else.

Anyways, due to the nature of this plugin, its kind of hard to test it. I try my best with code tests, but it only gets me so far. If you're willing to try out the new version, I'd love to hear how it turned out. TBH I'm not even sure if anyone will get notified of this message ... 😅

Thanks,

Troy

**Comment by sumoneelse** [comment]
Could you provide a paste of your mqtt sensors in configuration.yaml?

EDIT:  

I discovered the "status" sensor needs to be changed to "state" sensor. My MQTT sensor for this purpose now looks like:

```
    - state_topic: "musicbee/player/state"
      name: "musicbee_player_state"
```

I  needed to navigate to the Musicbee media player entity in home assistant (via the 'E' keyboard shortcut) and physically view the status of the media player entity to get the new fields to show up in the home assistant UI.  

Troy my 'source' selection worked the first time I tried it, although this was after I did the steps in my above paragraph. Maybe that's the only thing needed.  THANK YOU so much for fleshing out the remaining media player features for Musicbee!  The media control card on my [Desktop Echo Show](https://www.reddit.com/r/homeassistant/comments/1osbm6o/psa_first_gen_echo_show_5_and_8_devices_are/) control panel looks great with that progress bar!

<img width="1306" height="842" alt="Image" src="https://github.com/user-attachments/assets/f427cd61-9582-4aa5-bd4e-022c609c355f" />

**Comment by TroyFernandes** [comment]
@sumoneelse The example in the README is my own actual config. I have them in separate files and then call them with these lines in my configuration.yaml.

```
media_player: !include include/intergration/mqtt_musicbee.yaml
mqtt: !include include/intergration/mqtt_musicbee_sensor.yaml
```
 Ill share my sensor config (mqtt_musicbee_sensor.yaml) as well.
```
  sensor:
    - state_topic: "musicbee/song/title"
      name: "Musicbee_Song_Title"
    - state_topic: "musicbee/song/artist"
      name: "Musicbee_Song_Artist"
    - state_topic: "musicbee/song/album"
      name: "Musicbee_Song_Album"
    - state_topic: "musicbee/song/albumartist"
      name: "Musicbee_Song_Album_Artist"
    - state_topic: "musicbee/song/genre"
      name: "Musicbee_Song_Genre"
      icon: "mdi:music-box-multiple"
    - state_topic: "musicbee/song/year"
      name: "Musicbee_Song_Year"
      icon: "mdi:calendar"
    - state_topic: "musicbee/song/track"
      name: "Musicbee_Song_Track"
      icon: "mdi:pound"
    - state_topic: "musicbee/song/duration"
      name: "Musicbee_Song_Duration"
      icon: "mdi:timer-outline"
      unit_of_measurement: "s"
    - state_topic: "musicbee/song/content_type"
      name: "Musicbee_Content_Type"
      icon: "mdi:file-music"
    - state_topic: "musicbee/player/volume"
      name: "Musicbee_Player_Volume"
      icon: "mdi:volume-medium"
    - state_topic: "musicbee/player/state"
      name: "Musicbee_Player_State"
      icon: "mdi:play-circle"
    - state_topic: "musicbee/player/playing"
      name: "Musicbee_Player_Status"
      icon: "mdi:volume-medium"
    - state_topic: "musicbee/player/shuffle"
      name: "Musicbee_Shuffle_Mode"
      icon: "mdi:shuffle"
    - state_topic: "musicbee/player/repeat"
      name: "Musicbee_Repeat_Mode"
      icon: "mdi:repeat"
    - state_topic: "musicbee/player/muted"
      name: "Musicbee_Muted"
      icon: "mdi:volume-off"
    - state_topic: "musicbee/player/progress"
      name: "Musicbee_Player_Progress"
      icon: "mdi:progress-clock"
      unit_of_measurement: "s"
    - state_topic: "musicbee/player/output_device"
      name: "Musicbee_Output_Device"
      icon: "mdi:speaker"
```

I'll double check the docs to make sure I wrote that the state is different. Thanks for pointing that out.

~~Also, ill take a look over the weekend about updating the player state when closing Musicbee, should be an easy fix.~~ [v2.0.4](https://github.com/TroyFernandes/Musicbee-MQTT/releases/tag/v2.0.4) should fix this issue

Thanks for trying out the new changes, I appreciate it!

**Comment by TroyFernandes** [comment]
Oh also, just as a side-note, you should look at this integration https://github.com/kalkih/mini-media-player . The default media player card for home assistant won't show you all the new entities.

I've been using this for years and it has much more info when you click the card. That little image I posted in the musicbee mqtt plugin release page is what the card looks like when you click on it. Here's the yaml for the card in the UI

```
type: custom:mini-media-player
entity: media_player.musicbee
artwork: cover
icon: mdi:music-note
hide:
  power: true
  power_state: true
```

**Comment by sumoneelse** [comment]
A second vote here for the beautiful and infinitely customizable mini-media-player which I use in many places as well.

I've uncovered a potential issue which may be worth calling out explicitly for newer users somewhere in documentation, and that regards the Recorder database and potentially excluding at minimum **sensor.musicbee_player_progress** from state history.  While playing music, this sensor changes every few seconds or so while adding an entry for each tick.  I was excited to wake up to your post and implemented the new sensors this morning, then worked an 8ish-hour day with Musicbee shuffling tunes in the background.  This single sensor's history already comprises 2% of my database entries.

To save you some writing I'll will draft a suggestion here which you can feel free to use, modify, or ignore with prejudice.

..

**Database Warning:**
These sensor entities change states relatively frequently while Musicbee is playing.  If you have never previously used Recorder [database filters](https://www.home-assistant.io/integrations/recorder/#configure-filter) to exclude the states of certain entities from your history, you may want to consider doing so here. This is especially true if you configure a **player progress** sensor which updates every 1% while playing.  

Assuming you use the sensor names suggested in this documentation, one easy way to do this would be to include the following lines in the recorder stanza of your configuration.yaml file:

```
recorder:
  exclude:
    entity_globs:
      - sensor.musicbee*
```
The above will exclude all Musicbee state sensors from your history.  If you would like to exclude only certain sensors, you may reference Home Assistant's [common filtering examples](https://www.home-assistant.io/integrations/recorder#common-filtering-examples).
